In [2]:
import torch

In [2]:
b = torch.tensor([[0,0,0],[0,0,0]])

In [16]:
x = torch.tensor((0,), dtype=torch.float64)
val = torch.tensor(5)

In [26]:
b = torch.arange(5)

In [28]:
torch.flip(b, dims=(0,))

tensor([4, 3, 2, 1, 0])

In [30]:
x = [2,1,4,6]
print(max(x))

6


In [32]:
y = torch.zeros(max(x),max(x))
print(y)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [33]:
x = torch.tensor([
          [10, 20, 30],
          [ 2,  5,  1]])

In [35]:
vals, idx = x.min(dim=1)
print(vals)
print(idx)

tensor([10,  1])
tensor([0, 2])


In [36]:
len(idx)

2

In [37]:
x

tensor([[10, 20, 30],
        [ 2,  5,  1]])